# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [3]:
import numpy as np

# Лабораторные задачи

In [4]:
path = "D:/FinUniver/Технологии обработки больших данных/01_numpy/minutes_n_ingredients.csv"

In [74]:
# Задание 1
arr = np.loadtxt(path, int, skiprows=1, delimiter=',')
arr[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [75]:
# Задание 2
print("Второй столбец:")
print(np.mean(arr[:, 1]))
print(np.min(arr[:, 1]))
print(np.max(arr[:, 1]))
print(np.median(arr[:, 1]))
print("\nТретий столбец:")
print(np.mean(arr[:, 2]))
print(np.min(arr[:, 2]))
print(np.max(arr[:, 2]))
print(np.median(arr[:, 2]))

Второй столбец
21601.00169
0
2147483647
40.0

Третий столбец
9.05528
1
39
9.0


In [76]:
# Задание 3
quan = np.quantile(arr[:, 1], 0.75)
arr[:, 1] = np.where(arr[:, 1] <= quan, arr[:, 1], quan)
print(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [77]:
# Задание 4
print(np.count_nonzero(arr[:, 1] == 0))
arr[:, 1] = np.where(arr[:, 1] != 0, arr[:, 1], 1)

479


In [78]:
# Задание 5
print(len(np.unique(arr[:, 0])))

100000


In [79]:
# Задание 6
print(len(np.unique(arr[:, 2])))
print(np.unique(arr[:, 2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [80]:
# Задание 7
arr2 = arr[np.where(arr[:, 2] <= 5)]
print(arr2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [81]:
# Задание 8
ingr_in_minute = arr[:, 2] / arr[: ,1]
print(np.max(ingr_in_minute))

24.0


In [93]:
# Задание 9
sorting = np.array(sorted(arr, key=lambda a_entry: a_entry[1], reverse=True))
print(np.mean(sorting[:100, 2]))

10.03


In [110]:
# Задание 10
idx = np.random.randint(len(arr), size=10)
print(arr[idx, :])

[[136948     60     17]
 [402837     15      7]
 [237696     10      2]
 [437549     25      9]
 [185531      5      7]
 [137320     32      5]
 [190193      8      4]
 [290435     20      8]
 [439463     15      5]
 [321777     30      8]]


In [116]:
# Задание 11
print(len(arr[np.where(arr[:, 2] < np.mean(arr[:, 2]))]) / len(arr) * 100)

58.802


In [122]:
# Задание 12
simple = np.c_[arr, np.zeros(len(arr)).astype(int)]
simple[:, 3] = np.where((arr[:, 1] <= 20) & (arr[:, 2] <= 5), 1, 0)
simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

In [126]:
# Задание 13
print(len(simple[np.where(simple[:, 3] == 1)]) / len(simple) * 100)

9.552


In [145]:
# Задание 14
duration = np.array([np.zeros(len(arr)).astype(int), arr[:, 0], simple[:, 3]]).transpose()
duration[:, 0] = np.where((arr[:, 1] >= 10) & (arr[:, 1] < 20), 1, duration[:, 0])
duration[:, 0] = np.where(arr[:, 1] >= 20, 2, duration[:, 0])
duration

array([[     2, 127244,      0],
       [     2,  23891,      0],
       [     1,  94746,      0],
       ...,
       [     2, 498432,      0],
       [     0, 370915,      1],
       [     2,  81993,      0]])